# Generated by Django 3.2.3 on 2021-07-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat', models.CharField(max_length=5)),
                ('mPhoto', models.ImageField(upload_to='medicine/')),
                ('mName', models.TextField()),
                ('mSell', models.TextField()),
                ('mMrp', models.TextField()),
                ('mUses', models.TextField()),
                ('mSideEffect', models.TextField()),
                ('mHowtoUse', models.TextField()),
            ],
        ),
    ]
