# Generated by Django 3.2.3 on 2021-07-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20210709_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='atozmedicine',
            name='mAlter',
            field=models.TextField(default=''),
        ),
    ]
