# Generated by Django 3.2.3 on 2021-07-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_atozmedicine_malter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PcImage', models.ImageField(upload_to='Products/')),
                ('PcName', models.TextField()),
            ],
        ),
    ]
