# Generated by Django 3.2.3 on 2021-07-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BcImage', models.ImageField(upload_to='Products/')),
                ('BcName', models.TextField()),
            ],
        ),
    ]
