# Generated by Django 3.2.3 on 2021-09-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_beautycare'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APImage', models.ImageField(upload_to='AllProducts/')),
                ('APName', models.TextField()),
                ('APDetails', models.TextField()),
                ('APPrice', models.TextField()),
            ],
        ),
    ]
