# Generated by Django 3.2.3 on 2021-09-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_allproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='APCat',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
