# Generated by Django 3.2.8 on 2021-10-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_allproducts_apcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='atozmedicine',
            name='cName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='atozmedicine',
            name='mCount',
            field=models.TextField(default=''),
        ),
    ]
